# Generated by Django 5.0.7 on 2024-12-09 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('posting_date', models.DateField(verbose_name='Post Date')),
                ('update_date', models.DateField(auto_now_add=True, verbose_name='Last Update')),
                ('liked_by', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Liked by')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Post by')),
            ],
        ),
    ]
