# Generated by Django 5.0.7 on 2024-12-15 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_on',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='network.post', verbose_name='Post'),
            preserve_default=False,
        ),
    ]
