# Generated by Django 5.0.7 on 2024-12-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posting_date',
            field=models.DateField(auto_now=True, verbose_name='Post Date'),
        ),
    ]
