# Generated by Django 5.0.7 on 2024-12-09 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_post_posting_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='posting_date',
            new_name='post_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='update_date',
            new_name='update_at',
        ),
    ]
