# Generated by Django 5.0.7 on 2024-12-12 17:04

import network.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_posting_date_post_post_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color',
            field=models.CharField(default=network.models.generate_random_color, max_length=7),
        ),
    ]
